<?php
ob_start();
session_start();
require_once 'config/db.php';
require_once 'vendor/autoload.php';

$db = (new \InventorySystem\Database())->getConnection();

// Check if user is logged in
if (!isset($_SESSION['user_id'])) {
    header('Location: pos_login.php');
    exit();
}

// Fetch business details
$business_id = $_SESSION['business_id'] ?? null;
$business = null;
if ($business_id) {
    $stmt = $db->prepare("SELECT name, logo_path, phone_number, location FROM businesses WHERE id = ?");
    $stmt->execute([$business_id]);
    $business = $stmt->fetch(PDO::FETCH_ASSOC);
}

// Fetch sales data for report
$start_date = $_POST['start_date'] ?? date('Y-m-d', strtotime('-30 days'));
$end_date = $_POST['end_date'] ?? date('Y-m-d');
$stmt = $db->prepare("SELECT s.*, c.name AS customer_name 
                      FROM sales s LEFT JOIN customers c ON s.customer_id = c.customer_id 
                      WHERE DATE(s.sale_date) BETWEEN ? AND ?");
$stmt->execute([$start_date, $end_date]);
$sales = $stmt->fetchAll(PDO::FETCH_ASSOC);

$total_sales = array_sum(array_column($sales, 'total_price'));

// Generate PDF report
if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['generate'])) {
    $pdf = new \TCPDF();
    $pdf->SetCreator(PDF_CREATOR);
    $pdf->SetAuthor('MediPeak');
    $pdf->SetTitle('Sales Report');
    $pdf->SetMargins(10, 10, 10);
    $pdf->AddPage();

    // Header
    if ($business && $business['logo_path'] && file_exists($business['logo_path'])) {
        $pdf->Image($business['logo_path'], 10, 10, 30);
    }
    $pdf->SetFont('helvetica', 'B', 16);
    $pdf->Cell(0, 10, 'MediPeak - ' . ($business ? $business['name'] : 'Pharmacy'), 0, 1, 'R');
    $pdf->SetFont('helvetica', '', 10);
    $pdf->Cell(0, 5, $business ? $business['location'] : '123 Health St, Wellness City', 0, 1, 'R');
    $pdf->Cell(0, 5, $business ? $business['phone_number'] : '(555) 123-4567', 0, 1, 'R');
    $pdf->Ln(10);

    // Report Title
    $pdf->SetFont('helvetica', 'B', 12);
    $pdf->Cell(0, 10, 'Sales Report', 0, 1);
    $pdf->SetFont('helvetica', '', 10);
    $pdf->Cell(0, 5, 'Period: ' . date('m/d/Y', strtotime($start_date)) . ' to ' . date('m/d/Y', strtotime($end_date)), 0, 1);
    $pdf->Ln(5);

    // Sales Table
    $pdf->SetFont('helvetica', 'B', 10);
    $pdf->Cell(30, 7, 'Sale ID', 1);
    $pdf->Cell(40, 7, 'Date', 1);
    $pdf->Cell(60, 7, 'Customer', 1);
    $pdf->Cell(30, 7, 'Payment', 1);
    $pdf->Cell(30, 7, 'Total', 1);
    $pdf->Ln();
    $pdf->SetFont('helvetica', '', 10);
    foreach ($sales as $sale) {
        $pdf->Cell(30, 7, $sale['id'], 1);
        $pdf->Cell(40, 7, date('m/d/Y H:i', strtotime($sale['sale_date'])), 1);
        $pdf->Cell(60, 7, $sale['customer_name'] ?: 'Walk-in Customer', 1);
        $pdf->Cell(30, 7, $sale['payment_method'], 1);
        $pdf->Cell(30, 7, '$' . number_format($sale['total_price'], 2), 1);
        $pdf->Ln();
    }

    // Summary
    $pdf->Ln(5);
    $pdf->SetFont('helvetica', 'B', 12);
    $pdf->Cell(160, 7, 'Total Sales:', 0);
    $pdf->Cell(30, 7, '$' . number_format($total_sales, 2), 0);
    $pdf->Ln(10);

    // Footer
    $pdf->SetFont('helvetica', 'I', 8);
    $pdf->Cell(0, 10, 'Generated by MediPeak - ' . ($business ? $business['name'] : 'Pharmacy'), 0, 1, 'C');

    // Output PDF
    $pdf->Output('sales_report_' . date('Ymd') . '.pdf', 'D');
    exit();
}

require 'header.php';
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MediPeak - Generate Report</title>
    <style>
        body {
            font-family: 'Segoe UI', Arial, sans-serif;
            background: #e0f2fe;
            margin: 0;
            min-height: 100vh;
            display: flex;
        }
        .main-content {
            flex: 1;
            padding: 20px;
            margin-left: 256px;
        }
        .report-container {
            background: #ffffff;
            padding: 20px;
            border-radius: 12px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.1);
        }
        .report-container h1 {
            color: #1e40af;
            font-size: 1.8rem;
            margin-bottom: 20px;
        }
        .form-group {
            margin-bottom: 16px;
        }
        .form-group label {
            display: block;
            color: #1e40af;
            font-size: 0.9rem;
            font-weight: 500;
            margin-bottom: 8px;
        }
        .form-group input {
            padding: 10px;
            border: 2px solid #93c5fd;
            border-radius: 8px;
            background: #f8fafc;
            color: #1e40af;
            font-size: 0.9rem;
            width: 100%;
        }
        .submit-btn {
            padding: 12px;
            background: #3b82f6;
            color: #ffffff;
            border: none;
            border-radius: 8px;
            cursor: pointer;
            font-size: 1rem;
            font-weight: 500;
            transition: background 0.2s;
        }
        .submit-btn:hover {
            background: #1e3a8a;
        }
    </style>
</head>
<body>
    <div class="main-content">
        <div class="report-container">
            <h1>Generate Sales Report</h1>
            <form method="POST">
                <div class="form-group">
                    <label for="start_date">Start Date</label>
                    <input type="date" id="start_date" name="start_date" value="<?php echo htmlspecialchars($start_date); ?>" required>
                </div>
                <div class="form-group">
                    <label for="end_date">End Date</label>
                    <input type="date" id="end_date" name="end_date" value="<?php echo htmlspecialchars($end_date); ?>" required>
                </div>
                <button type="submit" name="generate" class="submit-btn">Generate Report</button>
            </form>
        </div>
    </div>
</body>
</html>

<?php
ob_end_flush();
require 'footer.php';
?>